config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [path('admin/', admin.site.urls),
               path('', include('mainapp.urls', namespace='mainapp')),
               path('users/', include('users.urls', namespace='users'))
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

from mainapp.apps import MainappConfig
from mainapp.views import *

app_name = MainappConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='products'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product'),
    path('products/create', ProductCreateView.as_view(), name='product_create'),
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('posts/', PostListView.as_view(), name='posts'),
    path('posts/create', PostCreateView.as_view(), name='post_create'),
    path('posts/update/<int:pk>/', PostUpdateView.as_view(), name='post_update'),
    path('posts/delete/<int:pk>/', PostDeleteView.as_view(), name='post_delete'),
    path('posts/<int:pk>/', PostDetailView.as_view(), name='post'),
    path('categories/', CategoryListView.as_view(), name='categories')
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.views.generic import TemplateView

from users.apps import UsersConfig
from users.views import RegisterView, LoginView, verify_email, ProfileView, GenerateNewPasswordView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify_email/<int:key>', verify_email, name='verify_email'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('generate_new_password/', GenerateNewPasswordView.as_view(), name='generate_new_password'),
    path('confirm_email/',
         TemplateView.as_view(template_name='users/confirm_email.html'),
         name='confirm_email'
         ),
]

mainapp/models.py
from django.db import models
from users.models import User
from utils.utils import NULLABLE
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(max_length=255, verbose_name='описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(max_length=255, verbose_name='описание')
    image_preview = models.ImageField(upload_to='preview/', verbose_name='превью изображений', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, **NULLABLE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.IntegerField(verbose_name='цена')
    create_at = models.DateTimeField(default=timezone.now, verbose_name='дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения')
    is_published = models.BooleanField(default=False, verbose_name='признак публикации')

    def get_active_version(self):
        return self.versions.filter(is_current_version=True).first()

    def __str__(self):
        return (f'{self.name} {self.description} {self.image_preview} '
                f'{self.category} {self.price} {self.create_at} {self.updated_at}')

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'
        ordering = ('name',)

        permissions = [
            (
                'set_moderator',
                'Can moderator'
            ),
            (
                'set_product_status',
                'Can product_status'
            ),
            (
                'set_product_description',
                'Can product_description'
            ),
            (
                'set_product_category',
                'Can product_category'
            )
        ]


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='versions', verbose_name='продукт')
    version_number = models.CharField(max_length=50, verbose_name='номер версии')
    version_name = models.CharField(max_length=150, verbose_name='название версии')
    is_current_version = models.BooleanField(default=False, verbose_name='признак текущей версии')

    def __str__(self):
        return f'{self.product.name} - Версия {self.version_number}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'


class Post(models.Model):
    title = models.CharField(max_length=255, verbose_name='заголовок')
    slug = models.CharField(max_length=255, unique=True, verbose_name='slug', **NULLABLE)
    body = models.TextField(verbose_name='содержимое')
    img_preview = models.ImageField(upload_to='post_preview/', verbose_name='превью изображения', **NULLABLE)
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='признак публикации')
    view_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'{self.title} {self.body} {self.create_date} {self.view_count}'

    class Meta:
        verbose_name = 'пост'
        verbose_name_plural = 'посты'
        ordering = ('title',)

mainapp/forms.py
from django import forms

from mainapp.models import Product, Version

forbidden_words = ('казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар')


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product

        fields = ('name', 'description', 'image_preview', 'category', 'price', 'is_published',)

    # def clean_field(self, field_name):
    #     cleaned_data = self.cleaned_data[field_name]
    #
    #     words = [word for word in forbidden_words if word.lower() in cleaned_data]
    #
    #     if words:
    #         raise forms.ValidationError(f'Запрещенные слова: {", ".join(words)}')
    #
    # def clean_name(self):
    #     return self.clean_field('name')
    #
    # def clean_description(self):
    #     return self.clean_field('description')


class ShortProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('description', 'category', 'is_published',)


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version

        fields = '__all__'

mainapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.core.mail import send_mail
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page, never_cache
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from mainapp.forms import ProductForm, VersionForm, ShortProductForm
from mainapp.models import Product, Post, Version, Category
from mainapp.services import get_cached_categories
from django.contrib.contenttypes.models import ContentType


class ProductListView(ListView):
    model = Product
    extra_context = {
        'title': 'Каталог товаров'
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        moderator = self.request.user.groups.filter(name='moderator').exists()
        user = self.request.user

        if user.is_superuser or moderator:
            return queryset
        else:
            return queryset.filter(is_published=True)


class ProductDetailView(DetailView):
    model = Product


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    # permission_required = 'mainapp.add_product'
    success_url = reverse_lazy('mainapp:products')

    @method_decorator(never_cache)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    success_url = reverse_lazy('mainapp:products')

    def get_form_class(self):
        if self.request.user == self.object.user or self.request.user.is_superuser:
            return ProductForm
        else:
            return ShortProductForm

    def test_func(self):
        return (
            self.request.user == self.get_object().user or
            self.request.user.is_superuser or
            self.request.user.groups.filter(name='moderator').exists()
        )


class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product
    permission_required = 'mainapp.delete_product'
    success_url = reverse_lazy('mainapp:products')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        formset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)

        if self.request.method == 'POST':
            context_data['formset'] = formset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = formset(instance=self.object)

        return context_data

    def test_func(self):
        return self.request.user.is_superuser


class PostListView(ListView):
    model = Post
    extra_context = {
        'title': 'Блог'
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)

        return queryset


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ('title', 'body',)
    success_url = reverse_lazy('mainapp:posts')

    @method_decorator(never_cache)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ('title', 'body',)

    def get_success_url(self):
        return reverse('mainapp:post', args=[self.object.pk])


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('mainapp:posts')


class PostDetailView(DetailView):
    model = Post

    def get(self, request, *args, **kwargs):
        post = self.get_object()

        if post.view_count == 100:
            subject = 'Пост достиг 100 просмотров'
            message = f'Пост "{post.title}" достиг 100 просмотров.'
            from_email = 'bantarion@yandex.ru'
            recipient_list = ['gamaizingg@gmail.com']
            send_mail(subject, message, from_email, recipient_list, fail_silently=True)

        post.view_count += 1
        post.save()

        return super().get(request, *args, **kwargs)


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Категории товаров'
        context_data['category_list'] = get_cached_categories()

        return context_data

mainapp/templates/mainapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex justify-content-between p-3 px-md-4 mb-3 border-bottom">
    <div class="d-flex flex-column">
        <h5 class="my-0 mr-md-auto mb-2 font-weight-normal">{{ title }}</h5>
        <nav class="ms-5">
            <a class="mr-2 btn btn-primary" href="{% url 'mainapp:products' %}">Главная</a>
            <a class="mr-2 btn btn-primary" href="{% url 'mainapp:posts' %}">Блог</a>
            <a class="btn btn-primary" href="{% url 'mainapp:categories' %}">Категории</a>
        </nav>
    </div>
    <div>
        <ul class="list-unstyled d-flex">
            {% if user.is_authenticated %}
                {#                <li><a class="btn btn-outline-warning" href={% url 'users:profile' %}>Профиль</a></li>#}
                <li><a class="btn btn-warning" href={% url 'users:logout' %}>Выйти</a></li>
            {% else %}
                <li><a class="btn btn-warning mr-2" href={% url 'users:register' %}>Регистрация</a></li>
                <li><a class="btn btn-warning" href={% url 'users:login' %}>Войти</a></li>
            {% endif %}
        </ul>
    </div>
</div>

<div class="container">
    {% block content %}
    {% endblock %}
</div>

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md text-center">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
        </div>
    </div>
</footer>

</body>

mainapp/templates/mainapp/category_list.html
{% extends 'mainapp/base.html' %}
{% load tags %}
{% block content %}
    <div class="list-group row">
        {% for category in category_list %}
            <a href="#" class="list-group-item list-group-item-action">{{ category.name }}</a>
        {% endfor %}
    </div>
{% endblock %}

mainapp/templates/mainapp/post_confirm_delete.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <form method="post" class="row">
        <div class="card">
            <div class="card_header">
                Удаление поста
            </div>
            <div class="card_body">
                {% csrf_token %}
                <p>Действительно удалить {{ object.title }}?</p>
                <button class="btn btn-danger" type="submit">Удалить</button>
                <a href="{% url 'mainapp:post' object.pk %}" class="btn btn-warning">Отмена</a>
            </div>
        </div>
    </form>
{% endblock %}

mainapp/templates/mainapp/post_detail.html
{% extends 'mainapp/base.html' %}
{% load tags %}
{% block content %}
    <div class="row text-center">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 text-left text-uppercase">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    <div class="text-left">
                        <p>{{ object.body }}</p>
                    </div>
                </div>
                <div class="card-footer d-flex justify-content-end">
                    <a href="{% url 'mainapp:post_update' object.pk %}" class="btn btn-outline-dark mr-2">
                        Редактировать
                    </a>
                    <a href="{% url 'mainapp:post_delete' object.pk %}" class="btn btn-outline-danger">
                        Удалить
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/post_form.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <form method="post" class="row">
        <div class="card">
            <div class="card_header">
                {% if object %}
                    Редактирование поста
                {% else %}
                    Добавление поста
                {% endif %}
            </div>
            <div class="card_body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                    {% if object %}
                        Сохранить
                    {% else %}
                        Добавить
                    {% endif %}
                </button>
            </div>
        </div>
    </form>
{% endblock %}

mainapp/templates/mainapp/post_list.html
{% extends 'mainapp/base.html' %}
{% load tags %}
{% block content %}
    <a href="{% url 'mainapp:post_create' %}" class="btn btn-success">Создать пост</a>
    <div class="row text-center pt-4">
        {% for object in object_list %}
            <div class="container col-4 text-left">
                <div class="card p-0 mb-4">
                    <div class="card-header bg-primary">
                        <h4 class="text-white my-0">{{ object.title }}</h4>
                    </div>
                    <div class="card-body">
                        <p>
                            {% if object.body|length > 50 %}
                                {{ object.body|slice:50 }}...
                            {% else %}
                                {{ object.body }}
                            {% endif %}
                        </p>
                    </div>
                    <div class="card-footer">
                        {% if object.view_count >= 1 %}
                            <p class="text-secondary text-lowercase">
                                Просмотры: {{ object.view_count }}
                            </p>
                        {% endif %}
                        <a class="btn btn-outline-info" href="{% url 'mainapp:post' object.pk %}"
                           role="button">
                            Больше
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

mainapp/templates/mainapp/product_confirm_delete.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <form method="post" class="row">
        <div class="card">
            <div class="card_header">
                Удаление продукта
            </div>
            <div class="card_body">
                {% csrf_token %}
                <p>Действительно удалить {{ object.title }}?</p>
                <button class="btn btn-danger" type="submit">Удалить</button>
                <a href="{% url 'mainapp:post' object.pk %}" class="btn btn-warning">Отмена</a>
            </div>
        </div>
    </form>
{% endblock %}

mainapp/templates/mainapp/product_detail.html
{% extends 'mainapp/base.html' %}
{% load tags %}
{% block content %}
    <div class="row text-center">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title text-right pricing-card-title">{{ object.price }} ₽</h1>
                    <img class="card-img"
                         src="{{ object.image_preview|mymedia }}"
                         alt=""/>
                    <div class="text-left ">
                        <div>
                            <span class="text-uppercase font-weight-bold">Категория:</span>
                            <span class="font-italic">{{ object.category }}</span>
                        </div>
                        <br>
                        <p>{{ object.description }}</p>
                    </div>
                    {% if user.is_authenticated %}
                        {% if request.user == object.user or request.user|has_group:'moderator' %}
                            <a href="{% url 'mainapp:product_update' object.pk %}" class="btn btn-outline-dark mr-2">
                                Редактировать
                            </a>
                            {% endif %}
                    {% endif %}
                    {% if user.is_superuser %}
                        <a href="{% url 'mainapp:product_delete' object.pk %}" class="btn btn-outline-dark mr-2">
                            Удалить
                        </a>
                    {% endif %}
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/product_form.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <form method="post" class="row" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card p-4">
                <div class="card_header h3 pb-3">
                    {% if object %}
                        Редактирование продукта
                    {% else %}
                        Добавление продукта
                    {% endif %}
                </div>
                <div class="card_body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Добавить
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>

        <div class="col-6">
            <div class="card p-4">
                <div class="card_header h3 pb-3">Версия продукта</div>
                <div class="card_body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                        {% if not forloop.last %}
                            <hr>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </form>
{% endblock %}

mainapp/templates/mainapp/product_list.html
{% extends 'mainapp/base.html' %}
{% load tags %}
{% block content %}
    {% if user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'mainapp:product_create' %}">Добавить продукт</a>
    {% endif %}
    <div class="row text-center p-4">
        {% for object in object_list %}
            <div class="container col-4">
                <div class="card p-0 mb-4">
                    <div class="card-header">
                        <h4 class="my-0">{{ object.name }}</h4>
                    </div>
                    <div class="card-body">
                        <img class="card-img"
                             alt="image preview"
                             src="{{ object.image_preview|mymedia }}"/>
                        <h1 class="card-title pricing-card-title">{{ object.price }} ₽</h1>
                        <p>{{ object.description|slice:100 }}...</p>
                        {% if object.get_active_version %}
                            <p class="text-danger text-left">
                                Текущая версия:
                                {{ object.get_active_version.version_number }}
                            </p>
                        {% endif %}
                    </div>
                    <div class="card-footer d-flex flex-column">
                        <p>{{ object.user }}</p>
                        <div class="d-flex">
                            <a href="{% url 'mainapp:product' object.pk %}" class="d-flex align-items-center justify-content-center btn mr-2 btn-warning col-6 float-left">
                                Описание
                            </a>
                            <button type="button" class="btn btn-lg btn-block btn-outline-primary col-6">Купить</button>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}